# Model arguments
model_name_or_path: google/gemma-3-270m-it
tokenizer_name_or_path: google/gemma-3-270m-it
model_revision: main
torch_dtype: bfloat16
attn_implementation: eager
use_liger: false
bf16: true
tf32: true
output_dir: /opt/ml/output/google/gemma-3-270m-it/peft-lora/

# Dataset arguments
dataset_id_or_path: /opt/ml/input/data/training/train_data.jsonl
max_seq_length: 512
packing: true

# LoRA arguments
use_peft: true
load_in_4bit: false
lora_target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]
# lora_modules_to_save: ["lm_head", "embed_tokens"]
lora_r: 16
lora_alpha: 32
lora_dropout: 0.1              # Regularization

# Training arguments
num_train_epochs: 3
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
learning_rate: 5.0e-5
lr_scheduler_type: cosine
warmup_ratio: 0.1

# Logging arguments
logging_strategy: steps
logging_steps: 10
report_to:
- tensorboard
run_name: gemma-3-270m-it-peft-lora-sentiment-analysis
eval_strategy: steps           # Enable eval during training
eval_steps: 10                 # Aligned with logging_steps
save_strategy: steps           # Save checkpoints
save_steps: 10                 # Aligned with logging_steps
save_total_limit: 3            # Keep only last 3 checkpoints
load_best_model_at_end: true   # Keep best checkpoint
metric_for_best_model: eval_loss
seed: 42
