# Model arguments
model_name_or_path: meta-llama/Llama-3.2-1B-Instruct
tokenizer_name_or_path: meta-llama/Llama-3.2-1B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger: false
bf16: true
tf32: true
output_dir: /opt/ml/output/meta-llama/Llama-3.2-1B-Instruct/peft-lora/

# Dataset arguments
dataset_id_or_path: /opt/ml/input/data/training/train_data.jsonl
max_seq_length: 2048
packing: false  # Disabled to ensure each sample gets individual gradient updates

# LoRA arguments
use_peft: true
load_in_4bit: false
lora_target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]
lora_r: 16
lora_alpha: 32  
lora_dropout: 0.1

# Training arguments
num_train_epochs: 28  # ~250 steps to match MLX (72 samples / batch 8 * 28 epochs ≈ 252)
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
learning_rate: 2.0e-5
lr_scheduler_type: cosine
warmup_ratio: 0.1

# Logging arguments
logging_strategy: steps
logging_steps: 10
report_to:
- tensorboard
run_name: llama-3.2-1b-instruct-peft-lora-customer-support
eval_strategy: "no"
save_strategy: steps
save_steps: 50
save_total_limit: 2
seed: 42
